swagger: "2.0"
info:
  title: "E-commerce App"
  version: "1.0.0"
  description: "This is a sample E-commerce server. "
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "kayahuseyin15@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api/v1/e-commerce-api"
tags:
  - name: "user"
    description: "Everything about User"
  - name: "category"
    description: "Everything about Category"
  - name: "product"
    description: "Everything about Product"
  - name: "cart"
    description: "Everything about Cart"
  - name: "order"
    description: "Everything about Order"
schemes:
  - "https"
  - "http"
paths:
  /user/signup:
    post:
      tags:
        - "user"
      summary: "Signup user"
      description: "It works to create new user"
      operationId: "signupUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "User object that needs to be added to the app"
          required: true
          schema:
            $ref: "#/definitions/SignUp"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponseSignUp"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /user/login:
    post:
      tags:
        - "user"
      summary: "Login user"
      description: "It works to login on system"
      operationId: "loginUser"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          description: "Login object that needs to be added to the app"
          required: true
          schema:
            $ref: "#/definitions/Login"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/SoleToken"
        "400":
          description: "Bad Request"
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /category/upload:
    post:
      tags:
        - "category"
      summary: "Upload category"
      description: "It works for creating bulk category"
      operationId: "uploadCategory"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - name: "file"
          in: "formData"
          description: "Upload category file"
          required: false
          type: "file"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        "401":
          description: "Status Unauthorized "
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Status Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /product/create:
    post:
      tags:
        - "product"
      summary: "Create product"
      description: "It works for creating product"
      operationId: "createProduct"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - in: "body"
          name: "body"
          description: "Create product"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /product/search?query:
    get:
      tags:
        - "product"
      summary: "Search product"
      description: "It works for searching product"
      operationId: "searchProduct"
      produces:
        - "application/json"
      parameters:
        - name: "query"
          in: "query"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /product/{id}:
    put:
      tags:
        - "product"
      summary: "Update product"
      description: "It works for updating product"
      operationId: "updateProduct"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - name: "id"
          in: "path"
          type: "string"
          required: true
        - in: "body"
          name: "body"
          description: "Product object that needs to be updated on system"
          required: true
          schema:
            $ref: "#/definitions/Product"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
    delete:
      tags:
        - "product"
      summary: "Delete product"
      description: "It works for deleting product"
      operationId: "deleteProduct"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - name: "id"
          in: "path"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        "401":
          description: "Status Unauthorized "
          schema:
            $ref: "#/definitions/ApiResponse"
        "403":
          description: "Status Forbidden"
          schema:
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /cart:
    post:
      tags:
        - "cart"
      summary: "Add product to cart"
      description: "It works for adding product to cart"
      operationId: "addItemCart"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - in: "body"
          name: "body"
          description: "Add product to cart"
          required: true
          schema:
            $ref: "#/definitions/CartItem"
      responses:
        "201":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse" 
    get:
      tags:
        - "cart"
      summary: "Get cartlist"
      description: "It works for getting cartlist"
      operationId: "getCartList"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/APICart"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
    put:
      tags:
        - "cart"
      summary: "update cartItem"
      description: "It works for patching cartItem"
      operationId: "patchCartItem"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - in: "body"
          name: "body"
          description: "Patch item on cart"
          required: true
          schema:
            $ref: "#/definitions/UpdatedCartItem"
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse" 
  /cart/{id}:
    delete:
      tags:
        - "cart"
      summary: "delete cartItem"
      description: "It works for deleting cartItem"
      operationId: "deleteCartItem"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
        - name: "id"
          in: "path"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"
  /order:
    get:
      tags:
        - "order"
      summary: "order list"
      description: "It works for getting order list"
      operationId: "orderList"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/OrderAPI"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"    
  /order/complete:
    post:
      tags:
        - "order"
      summary: "order complete"
      description: "It works for completing cart"
      operationId: "orderCart"
      produces:
        - "application/json"
      parameters:
        - name: "token"
          in: "header"
          type: "string"
          required: true
      responses:
        "200":
          description: "Successful Operation"
          schema:
            type: "string"
            $ref: "#/definitions/ApiResponse"
        default:
          description: Generic error response
          schema:
            $ref: "#/definitions/ApiResponse"      
definitions:
  SignUp:
    type: "object"
    required:
      - email
      - password
      - firstname
      - lastname
    properties:
      firstname:
        type: "string"
      lastname:
        type: "string"
      email:
        type: "string"
      password:
        type: "string"
  ApiResponseSignUp:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      token:
        type: "object"
        $ref: "#/definitions/Token"
  Token:
    type: "object"
    properties:
      access_token:
        type: "string"
      refresh_token:
        type: "string"
  SoleToken:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      token:
        type: "string"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
      message:
        type: "string"
      details:
        description: a (key, value) map.
        type: object
  Login:
    type: "object"
    required:
      - email
      - password
    properties:
      email:
        type: "string"
      password:
        type: "string"
  Product:
    type: "object"
    required:
      - name
      - description
      - quantity
      - categoryId
      - imageUrl
      - price
    properties:
      name:
        type: "string"
      description:
        type: "string"
      quantity:
        type: "integer"
        format: "int"
      categoryId:
        type: "string"
      imageUrl:
        type: "string"
      price:
        type: "number"
        format: "float64"
  OrderAPI:
    type: "object"
    properties:
      userid:
        type: "string"
      orderprice:
        type: "integer"
        format: "float64"
      orderdate:
        type: "string"
        format: "date-time"
      iscanceled:
        type: "boolean"
      orderitems:
        type: array
        items:
            type: "object"
            $ref: "#/definitions/OrderItemResponse"
  OrderItemResponse:
    type: "object"
    properties:
      orderid:
        type: "string"
      userid:
        type: "string"
      productid:
        type: "string"
      quantity:
        type: "integer"
        format: "uint"

  CartItemToResponse:
    type: "object"
    properties: 
      cartId:
        type: "string"
      productId:
        type: "string"
      product:
        type: "object"
        $ref: "#/definitions/Product"
      quantity:
        type: "integer"
        format: "int"
      totalPrice:
        type: "number"
        format: "float64"
  CartItem:
    type: "object"
    required:
      - productId
      - quantity
    properties:
      productId:
        type: "string"
      quantity:
        type: "integer"
        format: "uint"
  APICart:
    type: "object"
    properties:
      userId:
        type: "string"
      cartitems:
        type: "array"
        items:
            type: "object"
            $ref: "#/definitions/CartItemToResponse"
      completeOrder:
        type: "boolean"
      cartlength:
        type: "integer"
        format: "int"
      totalPrice:
        type: "number"
        format: "float64"
  OrderList:
    type: "object"
    properties:
      userıd:
         type: "string"
      orderitems:
        type: "array"
        items:
          type: "object"
          $ref: "#/definitions/OrderItemsOrderList"
      orderprice:
        type: "integer"
        format: "int"
      orderdate:
        type: "string"
        format: "date-time"

  OrderItemsOrderList:
    type: "object"
    properties:
      product:
        type: "object"
        $ref: "#/definitions/Product"
  UpdatedCartItem:
    type: "object"
    required:
      - productId
      - quantity
    properties: 
      productId:
        type: "string"
      quantity:
        type: "integer"
        format: "uint"

      
